import { describe, it, expect } from "vitest";
import { buildGhostMarkdown } from "../generator.js";
import type { GeneratorInput } from "../types.js";

function makeInput(overrides: Partial<GeneratorInput> = {}): GeneratorInput {
  return {
    contributor: "Alice Smith",
    slug: "alice-smith",
    gitObs: {},
    codeStyleObs: { observations: [], totalLinesAnalyzed: 0 },
    reviewObs: {},
    slackObs: {},
    docsSignals: { authoredDocs: [], docExcerpts: [] },
    sourcesUsed: ["git"],
    ...overrides,
  };
}

describe("buildGhostMarkdown", () => {
  it("includes the contributor name in the title", () => {
    const md = buildGhostMarkdown(makeInput());
    expect(md).toContain("# Contributor Soul: Alice Smith");
  });

  it("includes the slug in Identity section", () => {
    const md = buildGhostMarkdown(makeInput());
    expect(md).toContain("**Slug**: alice-smith");
  });

  it("includes sources used", () => {
    const md = buildGhostMarkdown(makeInput({ sourcesUsed: ["git", "github", "slack"] }));
    expect(md).toContain("git, github, slack");
  });

  it("contains all required sections", () => {
    const md = buildGhostMarkdown(makeInput());
    expect(md).toContain("## Identity");
    expect(md).toContain("## Review Philosophy");
    expect(md).toContain("## Communication Style");
    expect(md).toContain("## Code Patterns");
    expect(md).toContain("## Example Review Comments");
    expect(md).toContain("## Commit Message Style");
    expect(md).toContain("## Docs Authored");
  });

  it("includes generation footer", () => {
    const md = buildGhostMarkdown(makeInput());
    expect(md).toContain("<!-- Generated by @poltergeist-ai/cli -->");
    expect(md).toContain("<!-- Run date:");
  });

  it("includes review stats when provided", () => {
    const md = buildGhostMarkdown(
      makeInput({
        reviewObs: {
          totalReviewComments: 42,
          avgCommentLength: 85,
          tendsToBeBrief: true,
          questionRatio: 0.3,
          usesSeverityPrefixes: { nit: 10, blocking: 3 },
          sampleComments: ["Good point here", "Why this approach?"],
          source: "github",
        },
      }),
    );
    expect(md).toContain("**Total review comments analysed**: 42");
    expect(md).toContain("**Average comment length**: 85 chars");
    expect(md).toContain("**Tends to be brief**: true");
    expect(md).toContain("nit (10)");
    expect(md).toContain("blocking (3)");
  });

  it("includes sample review comments as blockquotes", () => {
    const md = buildGhostMarkdown(
      makeInput({
        reviewObs: {
          sampleComments: ["This looks fragile", "Consider extracting a helper"],
        },
      }),
    );
    expect(md).toContain("> This looks fragile");
    expect(md).toContain("> Consider extracting a helper");
  });

  it("truncates long review comments at 300 chars", () => {
    const longComment = "x".repeat(400);
    const md = buildGhostMarkdown(
      makeInput({
        reviewObs: { sampleComments: [longComment] },
      }),
    );
    expect(md).toContain("x".repeat(300) + "...");
    expect(md).not.toContain("x".repeat(301));
  });

  it("includes code style observations", () => {
    const md = buildGhostMarkdown(
      makeInput({
        codeStyleObs: {
          observations: [
            { category: "Import Style", observation: "Prefers named imports", confidence: "strong" },
            { category: "Function Style", observation: "Prefers arrow functions", confidence: "moderate" },
          ],
          primaryLanguage: "typescript",
          totalLinesAnalyzed: 500,
        },
      }),
    );
    expect(md).toContain("### Detected Code Style Preferences");
    expect(md).toContain("**Import Style**: Prefers named imports");
    expect(md).toContain("- Function Style: Prefers arrow functions");
    expect(md).toContain("Primary language: typescript");
  });

  it("includes git observations", () => {
    const md = buildGhostMarkdown(
      makeInput({
        gitObs: {
          commitMessageAvgLength: 45,
          likelyUsesImperativeMood: true,
          commitMessageSample: ["Fix auth bug", "Add dashboard"],
          primaryExtensions: [[".ts", 50], [".vue", 20]],
          inferredDomains: ["frontend", "testing"],
          namingStyle: { camelCase: 80, PascalCase: 15, snake_case: 5 },
        },
      }),
    );
    expect(md).toContain("**Avg length**: 45 chars");
    expect(md).toContain("**Uses imperative mood**: true");
    expect(md).toContain("`Fix auth bug`");
    expect(md).toContain(".ts (50)");
    expect(md).toContain("frontend, testing");
    expect(md).toContain("camelCase (80)");
    expect(md).toContain("Strongly prefers camelCase");
  });

  it("includes inferred domains in Identity", () => {
    const md = buildGhostMarkdown(
      makeInput({
        gitObs: { inferredDomains: ["backend", "infrastructure"] },
      }),
    );
    expect(md).toContain("**Primary domains**: backend, infrastructure");
  });

  it("uses placeholder when no domains inferred", () => {
    const md = buildGhostMarkdown(makeInput({ gitObs: {} }));
    expect(md).toContain("**Primary domains**: _[fill in manually]_");
  });

  it("includes Slack voice section when technical messages exist", () => {
    const md = buildGhostMarkdown(
      makeInput({
        slackObs: {
          sampleTechnicalMessages: ["We should refactor the API layer"],
        },
      }),
    );
    expect(md).toContain("## Slack / Chat Voice");
    expect(md).toContain("> We should refactor the API layer");
  });

  it("includes authored docs", () => {
    const md = buildGhostMarkdown(
      makeInput({
        docsSignals: {
          authoredDocs: ["docs/adr-001.md", "docs/design.md"],
          docExcerpts: [],
        },
      }),
    );
    expect(md).toContain("`docs/adr-001.md`");
    expect(md).toContain("`docs/design.md`");
  });

  it("shows placeholder when no docs authored", () => {
    const md = buildGhostMarkdown(makeInput());
    expect(md).toContain("_None found or docs-dir not provided._");
  });

  it("produces valid markdown with minimal input", () => {
    const md = buildGhostMarkdown(makeInput());
    // Should not throw and should contain basic structure
    expect(md.length).toBeGreaterThan(100);
    expect(md).toContain("# Contributor Soul:");
    expect(md).toContain("---");
  });

  it("populates recurring questions from sample comments ending with ?", () => {
    const md = buildGhostMarkdown(
      makeInput({
        reviewObs: {
          sampleComments: [
            "Why did you choose this approach?",
            "This looks fine",
            "Should we add a test for this?",
          ],
        },
      }),
    );
    expect(md).toContain('"Why did you choose this approach?"');
    expect(md).toContain('"Should we add a test for this?"');
  });
});
